//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoYshakoffnick
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YshakoffEntities : DbContext
    {
        public YshakoffEntities()
            : base("name=YshakoffEntitiesEntities")
        {
        }

        private static YshakoffEntities _context;
        public static YshakoffEntities GetContext()
        {
            if (_context == null)
            {
                _context = new YshakoffEntities();
            }
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Bookings> Bookings { get; set; }
        public virtual DbSet<BookingStatus> BookingStatus { get; set; }
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<Members> Members { get; set; }
        public virtual DbSet<Role_> Role_ { get; set; }
        public virtual DbSet<Trainers> Trainers { get; set; }
        public virtual DbSet<TrainingTypes> TrainingTypes { get; set; }
    }
}
